separate_arguments(VULL_COMPILER_FLAGS_LIST NATIVE_COMMAND "${VULL_COMPILER_FLAGS}")
separate_arguments(VULL_WARNING_FLAGS_LIST NATIVE_COMMAND "${VULL_WARNING_FLAGS}")

macro(vull_executable name)
    add_executable(${name})
    target_compile_features(${name} PRIVATE cxx_std_20)
    target_link_libraries(${name} PRIVATE ${ARGN})
    target_compile_options(${name} PRIVATE ${VULL_COMPILER_FLAGS_LIST} ${VULL_WARNING_FLAGS_LIST})
    target_link_options(${name} PRIVATE ${VULL_COMPILER_FLAGS_LIST} ${VULL_WARNING_FLAGS_LIST})
endmacro()

macro(vull_module name)
    add_library(vull-${name})
    add_library(vull::${name} ALIAS vull-${name})
    target_compile_features(vull-${name} PRIVATE cxx_std_20)
    target_compile_options(vull-${name} PRIVATE ${VULL_COMPILER_FLAGS_LIST} ${VULL_WARNING_FLAGS_LIST})
    target_link_libraries(vull-${name} PUBLIC ${ARGN})
endmacro()
