name: Build
on:
  workflow_call:
    inputs:
      preset:
        required: true
        type: string
      coverage:
        default: false
        required: false
        type: boolean
      upload:
        default: false
        required: false
        type: boolean

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yeetari/vull:master
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        shell: bash
        run: >-
          cmake .
          --preset ${{ inputs.preset }}
          -Bbuild
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
          -DVULL_ENABLE_COVERAGE=${{ inputs.coverage }}
          -GNinja

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cmake --build build --target test

      - name: Upload artifacts
        if: ${{ inputs.upload }}
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.preset }}
          path: |
            build/sandbox/vull-sandbox
            build/sandbox/builtin.vpak

      - name: Generate coverage report
        if: ${{ inputs.coverage }}
        run: cmake --build build --target coverage.xml

      - name: Upload coverage report
        if: ${{ inputs.coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: build/coverage.xml

      - name: Print coverage summary
        if: ${{ inputs.coverage }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage.xml
          hide_complexity: true
